my-school/src/Redux/Reducers/rootReducer.js
my-school/src/index.js

This pull request sets up the initial configuration of the app in index.js, including the following: 
- Imports Router
- Creates store & sets up Provider
- Sets up a rootReducer and applyMiddleware
We also created rootReducer.js in the Reducers file to help with the above process. 
This PR also includes the README.md template, which will be updated in more details at a later date.

Sets up initial configuration in index.js

---

CODE_OF_CONDUCT.md
README.md
my-school/src/App.js
my-school/src/index.js

This pull request adjusts some minor implementation and configuration details. Includes the following: 
- Wraps app with Router in App.js instead of index.js (per Mike's feedback from previous PR regarding possible issues with rtl)
- Wraps app in App.js with ThemeProvider from Chakra UI (this is just their default ThemeProvider for now; may be updated later to include any custom theming we need)
- Adds Chakra UI CSSReset in App.js
- Also includes Code of Conduct & Read Me template from Lambda FE Template

Minor updates to React Router & Chakra UI implementation

---

my-school/src/Components/EntryCard.js
my-school/src/Components/PortfolioContainer.js

This is a very basic layout for the portfolio container component.
Need to create hooks/functions/Link, etc

Portfolio container

---

my-school/src/App.css
my-school/src/Components/ActivityCard.js
my-school/src/Components/PortfolioLog.js
my-school/src/Components/TopNav.js
my-school/src/Redux/Reducers/portfolio-reducer.js
my-school/src/Redux/Reducers/rootReducer.js
my-school/src/actions/actions-portfolio.js

worked on the porfolio page, nav page, made reducer,set up actiod

worked on the porfolio page, nav page, made reducer,set up actiod

---

my-school/package-lock.json
my-school/package.json
my-school/src/App.js
my-school/src/Components/PortfolioLog.js

implements basic ga

---

my-school/src/Components/AddActivity/AddActivityForm.js
my-school/src/Components/Portfolio.js

fixes state update on pdf

---

my-school/package-lock.json
my-school/package.json
my-school/src/Components/ActivityCard.js
my-school/src/Components/AddActivity/NewActivityPreview.js
my-school/src/Components/Portfolio.js
my-school/src/Components/PortfolioLog.js
my-school/src/actions/actions-portfolio.js

added a loader to the activities portfolio screen

added the loader for the activities list

---

my-school/src/App.css
my-school/src/Components/ActivityCard.js
my-school/src/Components/ActivityContainer.js
my-school/src/Components/NavMenu.js
my-school/src/Components/PortfolioHeader.js

Aligned activity log

---

my-school/src/Components/ActivityOverview.js
my-school/src/Components/OverviewCard.js

finished styling the detail view page for the activities.

finished styling the page

---

my-school/src/Styles/theme.js
my-school/src/index.css

This PR creates a custom design theme by building off of Chakra UI's default theme and adding colors and fonts from the design system Marc created for My School.

Implements custom design theme via Chakra UI

---

my-school/src/App.js
my-school/src/Styles/theme.js

I forgot to push the change that actually implements the theme! Sorry >_<

Imports custom theme

---

my-school/src/Components/EditActivityModal.js

This PR fixes the Edit Activity Modal error messages, which were not showing up even though the form validation was working. 

Fixes Edit Activity Modal Error Messages

---

my-school/src/Components/AddActivity/AddActivityForm.js

Polishes up activity log. The form should now be responsive. However, I think there are some additional things that we'll want to polish up on this form. That includes: 
- Button styling: will want to ask Marc for his input here. What colors should the button background and font be? What should the hover state be? Border radius? 
- Submit button positioning: currently does not work well with mobile styling as is, as the file upload element wraps beneath the Submit button. Will want to find a better position. 
- File upload: still default styling. This will take some additional work to get this looking better. Will need to research further. 
- Number input fields: these may be hard to tap on a mobile device. Test this and increase size accordingly. 
Please delete options that are not …

Add Activity Form Styling

---

my-school/src/Components/HeaderButton.js
my-school/src/Components/OverviewCard.js
my-school/src/Components/PDFExporter.js

Removed extraneous link inside button

Removed extraneous link inside button

---

my-school/src/actions/actions-portfolio.js

changing the timeout from 2000 to 1000 for bettert user experience

changing the timeout from 2000 to 1000 for bettert user experience

---

my-school/src/Components/PDFExporter.js
my-school/src/Components/PortfolioLog.js

Fixed photo URL to use secure request

Fixed photo URL to use secure request

---

.codeclimate.yml
README.md

Polished readme for release approval

Polished readme for release approval

---

my-school/src/Components/AddActivity/AddActivityForm.js
my-school/src/Components/Portfolio.js

Fixes the issue where PDF activities state was not updating after a user edited or deleted an activity in the portfolio log, so changes and updates were not being reflected in the PDF. 

Fixes issue with PDF state update when editing or deleting activities

---

my-school/src/App.js
my-school/src/Components/login.js

made it so the dashboard isnt on every page

made it so the dashboard isnt on every page

---

my-school/src/App.js
my-school/src/index.js
package-lock.json

Adds Sentry exception monitoring support

---

.github/workflows/ci.yml
my-school/package-lock.json
my-school/package.json
my-school/src/__tests__/NavLeft.test.js

NavLeft test and code climate configs

NavLeft test and code climate configs

---

my-school/src/Components/Dashboards/Nav/NavMenu.js

I realized the logout functionality was only clearing local storage and that I should also push the user to the login page! Duh! 

A very small update to logout

---

my-school/src/Components/EnterUser/Landing.js
my-school/src/__tests__/util.test.js
my-school/src/utils/pillColor.js

Updated landing page. It's not perfect, but I'm no designer

Updated landing page

---

my-school/src/Components/EnterUser/Landing.js
my-school/src/Components/EnterUser/Login.js
my-school/src/Components/Portfolio/Activity/AddActivity/AddActivityForm.js
my-school/src/Components/Portfolio/PDFExporter.js
my-school/src/__tests__/util.test.js
my-school/src/utils/timeChange.js
my-school/src/utils/validateCredentials.js
my-school/src/utils/validateTitle.js

Restored redirect to dashboard

Restored redirect to dashboard

---

my-school/src/Components/EnterUser/Login.js

added the styling to match marcs figma

---

my-school/src/Components/EnterUser/Login.js

took out the borders

---

my-school/src/App.js
my-school/src/Components/MainLayout.js

This PR fixes the issue that caused the TopNav to re-render every time a user navigates to a new route. It introduces a new MainLayout component that renders the TopNav component and another component that varies based on the props being passed to the route. The MainLayout component will only be used to render PrivateRoutes, so that the TopNav will not appear on the login and signup pages.

Updates routes to prevent TopNav from constantly re-rendering

---

my-school/src/App.css
my-school/src/Components/Portfolio/Activity/ActivityCard.js
my-school/src/Components/Portfolio/Activity/EditActivityModal.js
my-school/src/utils/pillColor.js

pdated edit activity modal styles, implemented new subject colors

Updated edit activity modal styles, implemented new subject colors

---

my-school/src/Components/Portfolio/Activity/AddActivity/AddActivityForm.js
my-school/src/Components/Portfolio/Activity/DateSelector.js

This work continues polishing up the Add Activity Form and Date Selector components with UI updates that align with design files. It also improves the responsiveness of the components, so it should work better on a variety of devices. 

Add Activity Form & Date Selector UI updates

---

my-school/src/Components/Portfolio/Activity/AddActivity/AddActivityForm.js

Not sure what happened here, but the Add Activity Form started having trouble submitting for some unknown reason. Anyways, I made some updates, and it should now be working. 

Bug Fix: Add Activity Form Submit Errors

---

my-school/src/Components/Portfolio/Activity/AddActivity/AddActivityForm.js
my-school/src/Components/Portfolio/Activity/AddActivity/NewActivityPreview.js

This PR styles the NewActivityPreview component based on hi-fi mockups. It also fixes the issue with the image upload and photo preview that was happening. 
The Add Activity flow does not account for the "Make Changes" flow as indicated in Marc's designs yet. I haven't thought this through all the way yet, but if we want to implement the flow in the mockups, it may take some re-configuring. Not sure if we'll want to address that in this dev cycle, the next one or pass it on to a future group. 

NewActivityPreview UI Updates

---

my-school/src/Components/Dashboards/AdminDash.js
my-school/src/Components/Dashboards/StudentCard.js
my-school/src/Redux/Reducers/reducers-users.js
my-school/src/actions/actions-users.js

Updated state in users reducer

Updated state in users reducer

---

my-school/src/Components/EnterUser/Login.js

This is a minor change that fixes a bug that resulted from a change I made last night. I've updated the login function, so users with user_type_id 1 are pushed to /dashboard & users with user_type_id 2 are pushed to their portfolio. 

Fixes student login

---

my-school/src/Components/Dashboards/StudentCard.js
my-school/src/Components/EnterUser/Login.js
my-school/src/Components/Portfolio/Activity/ActivityCard.js
my-school/src/Components/Portfolio/Activity/DeleteEntryButton.js
my-school/src/Components/Portfolio/Activity/EditActivityModal.js
my-school/src/Components/Portfolio/PortfolioBody.js
my-school/src/Components/Portfolio/PortfolioContainer.js
my-school/src/Components/Portfolio/PortfolioHeader.js

This PR fixes the bug that was preventing students (users with user_type_id=2) from logging into their accounts. I also went ahead and continued cleaning up data flow clean up resulting from the state management PRs yesterday. This involved removing unnecessary axios calls as well as removing instances when we're trying to pull information from localStorage that we're no longer storing in localStorage. 
PLEASE NOTE: there is one instance of a broken localStorage item in ActivityOverview. It currently affects the breadcrumbs when a user clicks on an activity to view its details. I'm currently thinking through the best way to fix this. It needs a student id, which in all other instances we're pulling from params, but the student id is not in the params for this route. Therefore, we'll …

Fixes Student Login Bug & Continues State Management Clean Up

---

my-school/src/Components/Dashboards/Nav/NavMenu.js
my-school/src/Components/EnterUser/Login.js
my-school/src/Redux/Reducers/reducers-users.js

This PR fixes the issues we were seeing around logging out and students logging in. 

Bug Fix: Logout and Student Login

---

my-school/src/Components/Dashboards/AdminDash.js
my-school/src/Components/Dashboards/Nav/Breadcrumbs.js
my-school/src/Components/MainLayout.js
my-school/src/Components/Portfolio/Activity/AddActivity/AddActivityForm.js
my-school/src/Styles/theme.js

This PR builds out and styles a Breadcrumbs component and adds it to the MainLayout HOC. 
I am currently using Chakra UI's breadcrumb component and conditionally rendering them based on pathname and user type. I'm not sure if this is the best way to do this (perhaps there's a way to do it more programmatically). However, our app is small enough and there are a limited amount of views and user types, so it wasn't too much work to do it this way. 
Please note, I have NOT yet completed cleaning up the old breadcrumbs because I didn't want to touch too many files with this PR, but that is on my to do list. 

Breadcrumbs

---

my-school/src/Components/EnterUser/Settings.js

fixed the validation issue

---

my-school/src/Components/Dashboards/StudentCard.js

This PR addresses the bug we were seeing with the recent/last activity on the StudentCard component. I'm not sure if it's the _best_ solution out there, but it does work for the most part. Plus, it's only a couple lines of code which only touch the StudentCard.js file, so it should be super easy to remove if we find a better solution. 

Recent Activity Fix

---

my-school/src/App.css
my-school/src/Components/Portfolio/Activity/ActivityCard.js
my-school/src/Components/Portfolio/Activity/DeleteEntryButton.js
my-school/src/Components/Portfolio/Activity/EditActivityModal.js
my-school/src/Components/Portfolio/PortfolioBody.js

This PR updates the UI of the Portfolio Body and child elements to make it more responsive and clean up the UI a little bit. The component is not perfectly responsive, and it gets a little wonky on smaller screens (particularly for the parent view), but for a large table-esque grid component, it's not terrible. 

Polishes up Portfolio Body

---

my-school/src/components/settings/index.js

Removed old settings breadcrumbs

Removed old settings breadcrumbs

---

my-school/src/App.css
my-school/src/components/dashboard/StudentCard.js
my-school/src/components/dashboard/index.js

- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] Complete, ready to review and merge
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ X] My changes generate no new warnings
- [X ] There are no merge conflicts

adjusted margins and direction of student cards

---

my-school/src/components/EnterUser/Settings.js
my-school/src/components/settings/DeleteUser.js
my-school/src/components/settings/UpdateButton.js
my-school/src/components/settings/index.js

change color of buttons for settings, made the photo post faster

change color of buttons for settings, made the photo post faster

---

my-school/src/components/activityList/ActivityCard.js
my-school/src/components/addActivity/NewActivityPreview.js
my-school/src/components/dashboard/StudentCard.js
my-school/src/components/editActivity/index.js
my-school/src/components/overviewCard/Grid.js
my-school/src/components/pdf/PDFDocument.js

Completion dates were being displayed as a day behind the actual date. I think this was related to how MomentJS was reading the date with no timestamp. I added parseZone to all instances, and it should now work. Updated dates displayed related to the following components: Edit Activity modal, New Activity Preview, Activity Overview, Activity Card in the portfolio log and in the PDF document. 

Fixes issue with completion date display dates

---

my-school/src/components/pdf/PDFExporter.js

- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] Complete, but not tested (may need new tests)
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] My changes generate no new warnings
- [X ] There are no merge conflicts

added loader to pdfexporter
